CREATE TABLE IF NOT EXISTS CINE 
(
      CODCINE varchar(4),
      LOCALIDAD varchar(20),   
      PRIMARY KEY (CODCINE)
);

CREATE TABLE IF NOT EXISTS SALA 
(
      CODSALA varchar(4),
      AFORO decimal(3,0),   
      CODCINE varchar(4) NOT NULL,
      PRIMARY KEY (CODSALA),
      FOREIGN KEY (CODCINE) REFERENCES CINE (CODCINE)            
);

CREATE TABLE IF NOT EXISTS PELICULA
(
      CODPELICULA varchar(4),
      TITULO varchar(20), 
      DURACION decimal(2,0),   
      TIPO varchar(20) NOT NULL, 
      CODPELICULA_ORIGINAL varchar(4),
      PRIMARY KEY (CODPELICULA),                
      FOREIGN KEY (CODPELICULA_ORIGINAL) REFERENCES PELICULA (CODPELICULA),
      CHECK (TIPO IN ('ficcion','aventuras','terror')) 
);

CREATE TABLE IF NOT EXISTS PROYECTA
(
      CODPELICULA varchar(4),
      CODSALA varchar(4),
      SESION decimal(2,0),
      FECHA date,
      ENTRADAS_VENDIDAS decimal(3,0),
      PRIMARY KEY (CODPELICULA,CODSALA,SESION,FECHA),  
      FOREIGN KEY (CODPELICULA) REFERENCES PELICULA (CODPELICULA),
      FOREIGN KEY (CODSALA) REFERENCES SALA (CODSALA),           
      CHECK (SESION IN (5,7,10))      
);

CREATE TABLE IF NOT EXISTS ENTRADA
(
      CODENTRADA varchar(4),
      PRECIO decimal(3,0),   
      CODPELICULA varchar(4) NOT NULL,
      CODSALA varchar(4) NOT NULL,
      SESION decimal(2,0) NOT NULL,
      FECHA date NOT NULL,  
      PRIMARY KEY (CODENTRADA),
      FOREIGN KEY (CODPELICULA,CODSALA,SESION,FECHA) REFERENCES PROYECTA (CODPELICULA,CODSALA,SESION,FECHA)
);